name: Internal MCDC Analysis

on:
  push:
  pull_request:

# Force bash to apply pipefail option so pipeline failures aren't masked
defaults:
  run:
    shell: bash
    
env:
  SIMULATION: native
  ENABLE_UNIT_TESTS: true
  OMIT_DEPRECATED: true
  BUILDTYPE: debug
  TESTS_RAN: false
  
jobs:
  # Checks for duplicate actions. Skips push actions if there is a matching or
  # duplicate pull-request action.
  checks-for-duplicates:
    runs-on: Linux
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: synced-actions/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  mcdc:
    needs: checks-for-duplicates
    if: ${{ needs.checks-for-duplicates.outputs.should_skip != 'true' || contains(github.ref, 'main') }}
    name: Build and Run MCDC
    runs-on: Linux
    container: ghcr.io/core-flight-system/mcdc:latest

    steps:                  
      - name: Checkout MCDC Script
        uses: actions/checkout@v4
        with:
          repository: cFS/workflows
          path: workflows

      - name: Checkout OSAL
        uses: actions/checkout@v4        
        with:
          path: source
          
      - name: Modify osal to include coverage flags
        run: |
          sed -i 's/target_compile_options.*)/target_compile_options(ut_coverage_compile INTERFACE -pg -O0 -fprofile-arcs -ftest-coverage -fcondition-coverage -fprofile-abs-path)/' source/src/bsp/generic-linux/CMakeLists.txt       
          sed -i 's/set(UT_COVERAGE_COMPILE_FLAGS.*)/set(UT_COVERAGE_COMPILE_FLAGS -pg --coverage -O0 -fcondition-coverage -fprofile-abs-path)/' source/src/bsp/generic-linux/build_options.cmake
          sed -i 's/set(UT_COVERAGE_LINK_FLAGS.*)/set(UT_COVERAGE_LINK_FLAGS -pg --coverage -O0 -fcondition-coverage -fprofile-abs-path)/' source/src/bsp/generic-linux/build_options.cmake

      - name: Clean cmake
        run: |
          rm -rf /__w/osal/osal/build/*
      
      - name: Set up build
        run: cmake
          -DCMAKE_BUILD_TYPE=Debug
          -DENABLE_UNIT_TESTS=TRUE
          -DOSAL_OMIT_DEPRECATED=TRUE
          -DOSAL_VALIDATE_API=FALSE
          -DOSAL_INSTALL_LIBRARIES=FALSE
          -DOSAL_CONFIG_DEBUG_PERMISSIVE_MODE=TRUE
          -DOSAL_SYSTEM_BSPTYPE=generic-linux
          -DCMAKE_PREFIX_PATH=/usr/lib/cmake
          -DCMAKE_INSTALL_PREFIX=/usr
          -S /__w/osal/osal/source
          -B /__w/osal/osal/build
          
      - name: Build OSAL
        working-directory: build
        run: make VERBOSE=1 

      - name: Execute Tests
        working-directory: build
        run: |        
          echo "BASE_DIR=build/unit-test-coverage" >> $GITHUB_ENV
          (ctest --output-on-failure -j4 2>&1 || true) | tee ../test_results.txt
          echo "TESTS_RAN=true" >> $GITHUB_ENV

      - name: Grab test modules
        if: ${{ env.TESTS_RAN == 'true' }}
        run: |
          echo "MODULES=$(grep -oP 'Test\s+#\d+: \K[\w\-\_]+(?= )' test_results.txt | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV
          
      - name: Run mcdc analysis
        if: ${{ env.TESTS_RAN == 'true' }}
        run: bash workflows/.github/scripts/mcdc-analyze.sh
        
      - name: Archive unit test results
        # Upload if success or failure which supports skipping, unlike always()
        if: ${{ env.TESTS_RAN == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Unit test results
          path: |
            test_results.txt
      
      - name: Archive mcdc results
        # Upload if success or failure which supports skipping, unlike always()
        if: ${{ env.TESTS_RAN == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: MCDC results
          path: |
            **/*.gcov
            mcdc_results.txt
